#pragma once

#define ECHO_MOUSE_BUTTON_1         0
#define ECHO_MOUSE_BUTTON_2         1
#define ECHO_MOUSE_BUTTON_3         2
#define ECHO_MOUSE_BUTTON_4         3
#define ECHO_MOUSE_BUTTON_5         4
#define ECHO_MOUSE_BUTTON_6         5
#define ECHO_MOUSE_BUTTON_7         6
#define ECHO_MOUSE_BUTTON_8         7
#define ECHO_MOUSE_BUTTON_LAST      ECHO_MOUSE_BUTTON_8
#define ECHO_MOUSE_BUTTON_LEFT      ECHO_MOUSE_BUTTON_1
#define ECHO_MOUSE_BUTTON_RIGHT     ECHO_MOUSE_BUTTON_2
#define ECHO_MOUSE_BUTTON_MIDDLE    ECHO_MOUSE_BUTTON_3
